services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    env_file:
      - .env
    depends_on:
      - mariadb
      - wordpress
    ports:
      - 443:443
    volumes: 
      - wordpress:/var/www/html
    networks:
      - inception
    restart: on-failure

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes: 
      - wordpress:/var/www/html
    networks:
      - inception
    restart: on-failure

  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes: 
      - mariadb:/var/lib/mysql
    networks:
      - inception
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_PORT=${MARIADB_PORT}
      - MARIADB_ADRRESS=${MARIADB_ADRRESS}
    restart: on-failure

  redis:
    image: redis
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on: 
      - wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure

  adminer:
    image: adminer
    container_name: adminer
    build: ./requiremenets/bonus/adminer
    depends_on: mariadb
    networks:
      - inception
    restart: on-failure

  ftp:
    image: ftp
    container_name: ftp
    build: ./requirements/bonus/ftp
    env_file:
      - .env
    networks:
      - inception
    ports:
      - 21:21
      - 21000-21010:21000-21010
    volumes: 
      - wordpress:/var/www/html
    restart: on-failure

  #   prometheus:
  #   container_name: 42prometheus
  #   build:
  #     context: ./bonus/prometheus
  #   image: 42_prometheus
  #   volumes:
  #     - monitoring-volume:/monitor
  #   networks:
  #     - monitoring-network
  #   environment:
  #     - CADVISOR_PORT=${CADVISOR_PORT}
  #     - PROMETHEUS_PORT=${PROMETHEUS_PORT}
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/monitor/prometheus'
  #     - '--storage.tsdb.retention=200h'
  #     - '--web.listen-address=:${PROMETHEUS_PORT}'
  #   restart: unless-stopped

  # grafana:
  #   container_name: 42grafana
  #   build:
  #     context: ./bonus/grafana
  #   image: 42_grafana
  #   volumes:
  #     - monitoring-volume:/monitor
  #   networks:
  #       - nginx-network
  #       - monitoring-network
  #   environment:
  #     - PROMETHEUS_PORT=${PROMETHEUS_PORT}
  #     - GF_AUTH_DISABLE_LOGIN_FORM=true
  #     - GF_AUTH_ANONYMOUS_ENABLED=true
  #     - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  #   restart: unless-stopped

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/hvecchio/data/mysql
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/hvecchio/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge